### ISSUE TITLE
Must declare the scalar variable

### ISSUE THREAD

**Issue by dmarlow** [jonwagner/Insight.Database#299]
I've got something that looks like this:
```
var results = connection.QuerySql<DTOs.SomeDto>(
     "select * from table where tableId in (@ids) and otherColumn = @column",
     new { ids = ids, column= column.ToString() })
```
`ids` is an `IList<long>`
That for some of my servers, I get the following error. _If I reboot the machine, the problem goes away_. I've tried to reproduce locally, but am unable to. :(
I have a sneaking suspicion it could be related to the IL stuff in [CreateClassInputParameterGenerator](https://github.com/jonwagner/Insight.Database/blob/04bcf2a2ad4ea08f6c6722b791d646aa467341ac/Insight.Database/CodeGenerator/DbParameterGenerator.cs#L260)

```
System.Data.SqlClient.SqlException: Must declare the scalar variable "@ids".
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at Insight.Database.DBConnectionExtensions.ExecuteAndAutoClose[T](IDbConnection connection, Func`2 getCommand, Func`3 translate, CommandBehavior commandBehavior) in c:\projects.net\Insight.Database\Insight.Database\Extensions\DBConnectionExtensions.cs:line 1459
```

**Comment by AndrewFreese** [comment]
Is it possible ids is null or empty sometimes?

**Comment by dmarlow** [comment]
No, I have a check right before making the call to ensure it's not empty or null.

**Comment by jonwagner** [comment]
It's most likely a null/empty list. Can you paste the rest of the method?

**Comment by jonwagner** [comment]
If you still have the issue, please post some more details and reopen the case.

**Comment by dmarlow** [comment]
I can assure you it's not an empty list. Here's the method. I've scrubbed some company stuff, but it's logically the same.

The interesting thing here is that the issue only affects a subset of the servers where the same code is deployed to and upon killing the w3wp worker process, the issue goes away. If the issue happens again, would getting a dump be helpful? I know that some of the internals of is dynamically generated, so I'm not sure if that'll help. I've added some logging recently and haven't seen any issues. So, the idea here being that I can see the generated SQL and get some visibility as to what got generated. I'll report back here if I see it again with the generated SQL. Let me know what else I can get before I kill those processes.

```
public Dictionary<long, string> GetTableValues(IEnumerable<long> keys, SomeEnum column)
{
	var ids = keys as IList<long> ?? keys?.ToList();
	if (ids.IsNullOrEmpty())
	{
		return new Dictionary<long, string>();
	}
	var results = connection
		.QuerySql<DTOs.SomeDto>(
			"select * from table where tableId in (@ids) and otherColumn = @column",
			new { ids = ids, column = column.ToString() })
		.ToDictionary(x => x.Key, x => x.Value);

	return results;
}
```

**Comment by jonwagner** [comment]
Yes, the parameter template is generated dynamically the first time you make a call with a given sql statement & type of parameter object. Here we have static SQL and an anonymous type. Do you use the exact SQL anywhere else in the code?

I'm doing some work on the library now, so I'll also dive into the code and add some test cases around this.

**Comment by dmarlow** [comment]
No, that exact SQL is not used. We have 3 variations of that query that are similar, but different.

`select * from table where tableId in (@ids) and otherColumn = @column`
`select * from table where tableId in (@ids) and otherColumn in (@columns)`
`select * from table where otherColumn in (@columns)`

**Comment by jonwagner** [comment]
Trolling through the code...

* If I run `select * from beer where id in (@ids)` directly in sql manager, I get `Must declare the scalar variable @ids`. That tells me we're not adding any parameters named `@ids` to the query.
* `InsightDbProvider.DeriveParametersFromSqlText` correctly detects the `@ids` parameter and adds it to the parameter template.
* Upon execution, in `DbParameterGenerator.ConvertListParameterByValue` we remove the original parameter, replace `@ids` with `NULL` or `@ids1, @ids2...` and then add in all of the parameters from the list. So, in general you should see `select...in (@ids1, @ids2)...` in a sql trace.
* We're seeing `@ids` in the error, so the sql text replacement isn't happening, not even to NULL, so it's not hitting ConvertListParameterByValue.
* I don't see a way for the code to not end up in that method if mapping is happening.

Some things to check:

* Are you using any custom mappings? It might be that ids is getting mapped to something else and then ignored on the object. That could be sequence dependent if your classes are loaded in different orders.

Hmm...that's all I can think of at the moment. Even if your lists were mutated, I would expect to see `@ids` replaced by something else unless there is something interfering with mapping.

**Comment by dmarlow** [comment]
First thing that came to my mind was a bug in IL generation in release mode. Like I said, now that I have logging in place I can at least see what it does if/when it happens again. I didn't have logging before, so I was at a loss as to what to do.

**Comment by dmarlow** [comment]
I just realized I never answered your question. We have no custom mapping configured or used in our application.

**Comment by jonwagner** [comment]
I can't think of any other reasons why that issue would pop up. If you see the issue again, see if you can record:

- stack trace
- sql statement - sql profiler trace would be fine
- sql parameters collection
- object passed into QuerySql

I'll close this for now, but feel free to reopen if you get more info.

**Comment by jonwagner** [comment]
While I was rebuilding some TVP code, I found an issue where an exception while sending a TVP can cause the TDS stream to go out of sync and then the next call generates an exception.

I was able to cause this by sending a null record up in a TVP, and then the error happened randomly in another test.

So there is a good chance that this was caused by other code, and the Insight causes should be fixed in the 6.0 release.

**Comment by dmarlow** [comment]
Ok, so the error came back today with vengeance. I hadn't seen it in a really long time, but several servers today got the issue. Rebooting them solved the problem. Nothing has changed on them in weeks.

I had logging enabled and saw that the generated SQL was unchanged and that's what was being sent to SQL engine. For example, this is the SQL I wrote that was supposed to be prepared:

`select * from table where tableId in (@ids) and otherColumn = @column`

The profiler literally logged that instead of what it usually logs:

`select * from table where tableId in (@1, @2) and otherColumn = @'SomeValue'`
